### ISSUE TITLE
Add animations in the app while switching to the other screen

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#119]

**Comment by samitkapoor** [comment]
Hey @nitin-787 I'd like to work on this issue.

Do you want the animation in all the navigations?

**Comment by nitin-787** [comment]
@samitkapoor any progress?

**Comment by samitkapoor** [comment]
@nitin-787 So sorry, I won't be able to work on this issue.

**Comment by amitamrutiya2210** [comment]
Hey @nitin-787 I genuinely want to work on this issue . Can you assign This issue to me?

**Comment by nitin-787** [comment]
@amitamrutiya2210 sure!!
