### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#39]
# Firebase google auth
### Add auth with google in the login and sign in pages

**Comment by Hariprasad19036** [comment]
I would like to work on this issue, kindly assign this to me!

**Comment by Pratham-19** [comment]
Hi can I work on it ?

**Comment by Mehul-Kumar-27** [comment]
Hi I would like to work with you on this project.

**Comment by nitin-787** [comment]
> Hi I would like to work with you on this project.
> 

Go ahead

**Comment by codewithnadeem14502** [comment]
hello sir , can you assign me this task , i will happy to work on this issue

**Comment by nitin-787** [comment]
> hello sir , can you assign me this task , i will happy to work on this issue

Check it I have assigned it to you

**Comment by codewithnadeem14502** [comment]
hello, sir sorry to say but i have knowledge only about web development only , i don't any thing about flutter sir . if you web development login Firebase google auth then i can try my best to add this contribution

**Comment by nitin-787** [comment]
> hello, sir sorry to say but i have knowledge only about web development only , i don't any thing about flutter sir . if you web development login Firebase google auth then i can try my best to add this contribution 

It's okay but you can learn on the go

**Comment by piyushkumar12111111** [comment]
Please assign this to me

**Comment by nitin-787** [comment]
### [Fix](https://github.com/nitin-787/mynotes/pull/61)
