### ISSUE TITLE
Date and time

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#41]
Save the date and time while user make new notes or update the notes feel free to DM me for details.

**Comment by Pratham-19** [comment]
Hi can I work on it?

**Comment by nitin-787** [comment]
> Hi can I work on it?

Yes

**Comment by Pratham-19** [comment]
where can I dm you is discord fine?

**Comment by nitin-787** [comment]
> where can I dm you is discord fine?

Yss

**Comment by nitin-787** [comment]
## Firebase date time
### I added the date time [commit](https://github.com/nitin-787/mynotes/commit/05ea75ea4eb4b7307c2ba4de270acd00c0ffcf3e) while user creates a New note but I am not closing the this issue bcuz I want to store date time like most of the social media apps does like I am taking example of my reddit notification 
### if the user just created the note it may display like : just now or just recently

### You can refer date of notifications from here
![Screenshot 2022-09-25 192057 copy](https://user-images.githubusercontent.com/76255199/192148034-197676e8-7a24-460e-84b8-406e8a29ebdc.png)

**Comment by nitin-787** [comment]
### [Fix](https://github.com/nitin-787/mynotes/commit/05ea75ea4eb4b7307c2ba4de270acd00c0ffcf3e)
