### ISSUE TITLE
Updating the ReadMe and documentation

### ISSUE THREAD

**Issue by krupalitrivedi** [nitin-787/mynotes#44]
Would love to help with the documentation and ReadMe files in the project for hacktoberfest!

**Comment by himanshu-kashyap-au28** [comment]
hi I would like to work on the project can u assign it me?

**Comment by tmsagarofficial** [comment]
I would love to help this repo with documentation and ReadMe files for hacktoberfest!.

**Comment by nitin-787** [comment]
> I would love to help this repo with documentation and ReadMe files for hacktoberfest!.

go ahead

**Comment by tmsagarofficial** [comment]
Pls check it has been done

**Comment by tmsagarofficial** [comment]
@nitin-787 pls let me know what else help is needed and what more features do u want me to try to add

**Comment by nitin-787** [comment]
> @nitin-787 pls let me know what else help is needed and what more features do u want me to try to add

I want help in backend

**Comment by tmsagarofficial** [comment]
@nitin-787 I don't hav too much of a hold on backend.....but pls ping me about the issue / what needs to be done on any msging platform .

**Comment by syedzubeen** [comment]
@nitin-787 
Is this issue still open ?
If yes, what sections of the readme are you looking to update? I see some content already populated in the README file.

**Comment by tmsagarofficial** [comment]
Hi again @nitin-787, I'm back. I would like to help u with documentation, Let me know what modifications are on ur mind so that I can start working on that once u assign it.

**Comment by aakritiguptaa** [comment]
Helloo @nitin-787 
I would love to work on the improvement of the documentation of the project.
The documentation can be improved into looking a lot more project-like.

Since I am a newbie too, it would also help other fellow newbies into understanding the project better and be able to contribute to the project.

Hoping I could be assigned this issue
Thanks!

Regards 
Aakriti

**Comment by aakritiguptaa** [comment]
Thank youuu

**Comment by Nitin-Singh18** [comment]
Hey @nitin-787,
I would like to make some improvements...
Can you assign it to me?
