### ISSUE TITLE
Loading Animation

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#50]
### Add shimmer loading effect while loading the Notes in Public Wall

**Comment by superiorsd10** [comment]
@nitin-787 Can I work on this issue?

**Comment by nitin-787** [comment]
> @nitin-787 Can I work on this issue?

For sure

**Comment by Mehul-Kumar-27** [comment]
Hey , can I work on this issue ??

**Comment by nitin-787** [comment]
### [Fix](https://github.com/nitin-787/mynotes/pull/62)
