### ISSUE TITLE
User profile 

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#52]
### Simple user profile like, username, collage / university , maybe we can add more things inside it but for now I didn't have anything  in my mind about it, I would love to hear from you!

**Comment by Mohamed-003** [comment]
do u need a fancy username?
can u pls elaborate, i'm unable to understand.

**Comment by nitin-787** [comment]
> do u need a fancy username? can u pls elaborate, i'm unable to understand.

user profile where user can add his or name along with collage

**Comment by piyushkumar12111111** [comment]
Please assign this to me

**Comment by piyushkumar12111111** [comment]
Please assign this to me

**Comment by piyushkumar12111111** [comment]
Thx sir For assigning

**Comment by NikhitaBarat** [comment]
@piyushkumar12111111 hey, are u still working on this issue?

**Comment by nitin-787** [comment]
> @piyushkumar12111111 hey, are u still working on this issue?

No, you can do it if you want to and ping on discord for firebase access

**Comment by piyushkumar12111111** [comment]
sir I was working on this

**Comment by piyushkumar12111111** [comment]
This is wrong

**Comment by nitin-787** [comment]
> This is wrong

Ok ok

**Comment by anujsinghrawat** [comment]
please post regular updates if you are still working on it @piyushkumar12111111

**Comment by SmartAree** [comment]
can I contribute to this issue?

**Comment by nitin-787** [comment]
> can I contribute to this issue?

I would love to see you as contributor

**Comment by SmartAree** [comment]
Can you assign this to me? I am really excited because it's my first time participating in Hactberfest :D

**Comment by SmartAree** [comment]
Thank you so much for assigning me. Do you need the UI part only or the backend too?? and There's no sample template for user profiles then Can I create my own simple design with your themes??

**Comment by nitin-787** [comment]
> Thank you so much for assigning me. Do you need the UI part only or the backend too?? and There's no sample template for user profiles then Can I create my own simple design with your themes??

Of course Project need both the UI and the backend, it would be great if can do backend too. anyways start with the front end start with the figma design.

**Comment by SmartAree** [comment]
Ok, Sir, I do the backend too And there is no user profile screen template in Figma.

**Comment by nitin-787** [comment]
> Ok, Sir, I do the backend too And there is no user profile screen template in Figma.

Yeah we need to work on that

**Comment by SmartAree** [comment]
Ok then do let me know when the user profile template is created.

**Comment by nitin-787** [comment]
> Ok then do let me know when the user profile template is created.

Right now I'm working on the chat feature.

**Comment by SmartAree** [comment]
Okay, @nitin-787 I will wait.

**Comment by nitin-787** [comment]
@SmartAree are you still working on it?

**Comment by SmartAree** [comment]
Yes, I am waiting for you. You said that you are working on a chat feature

**Comment by SmartAree** [comment]
I am waiting for the user profile template. If you want me can I create my own design with your theme colors?

**Comment by nitin-787** [comment]
> Yes, I am waiting for you. You said that you are working on a chat feature

you don't need to wait for it, that a separate thing, you can create the UI

**Comment by SmartAree** [comment]
Ok sir

**Comment by SmartAree** [comment]
Hello, I created this minimalistic design and also created an Image picker function. Kindly check it and let me know if any changes you want. 

![Screenshot_1665305317](https://user-images.githubusercontent.com/41040479/194747292-33b11a84-850f-4f66-9a7a-6d6ead882f49.png)

and Do you want a Firebase storage function?? The user can change their profile picture which will store in the storage section of firebase.

**Comment by nitin-787** [comment]
> Hello, I created this minimalistic design and also created an Image picker function. Kindly check it and let me know if any changes you want. 
> 
> ![Screenshot_1665305317](https://user-images.githubusercontent.com/41040479/194747292-33b11a84-850f-4f66-9a7a-6d6ead882f49.png)
> 
> and Do you want a Firebase storage function?? The user can change their profile picture which will store in the storage section of firebase.
> 

This is looking pretty awesome and backend is needed you can ping me on discord for firebase access

**Comment by SmartAree** [comment]
Thankyou so much .. yeah sure I will join you there.

**Comment by SmartAree** [comment]
Your discord id?

**Comment by nitin-787** [comment]
> Your discord id?

NEX_07#4063
