### ISSUE TITLE
No internet animation

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#60]

**Comment by slayeh17** [comment]
Hello, I would really like to resolve this issue but I have no knowledge of what to do🥲. I probably won't be able to do much but could anyone please guide me if possible?
Thank You.

**Comment by nitin-787** [comment]
> Hello, I would really like to resolve this issue but I have no knowledge of what to do🥲. I probably won't be able to do much but could anyone please guide me if possible? Thank You.

I would love to guide you

**Comment by Mehul-Kumar-27** [comment]
Hey , I would love to work on this issue.

**Comment by slayeh17** [comment]
> > Hello, I would really like to resolve this issue but I have no knowledge of what to do🥲. I probably won't be able to do much but could anyone please guide me if possible? Thank You.
> 
> I would love to guide you

Yaaay thank you.

**Comment by nitin-787** [comment]
> Hey , I would love to work on this issue.
> 

Okay

**Comment by nitin-787** [comment]
### Fix: #89
