### ISSUE TITLE
Add Password show/hide button

### ISSUE THREAD

**Issue by piyushkumar12111111** [nitin-787/mynotes#69]
### Description

Password show and hide button is not there, Inside login as well as register view, Sometimes very bad experience for the user if the user in not able to see his password while creating

**Comment by piyushkumar12111111** [comment]
Eye button not working in the Password section , it is some time very bad experience for the user at the starting of the app if user faces this issue in login in

**Comment by piyushkumar12111111** [comment]
Assign this issue to me

**Comment by Perumallpardhiv** [comment]
Assign this issue to me

**Comment by nitin-787** [comment]
### Fix: pull #86
