### ISSUE TITLE
Shimmer loading animation: Enhancement and improvement

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#74]
### Screenshots

![Screenshot 2022-10-02 173259](https://user-images.githubusercontent.com/76255199/193453114-24253b91-73bf-4f3c-ae2c-917e6138ed28.png)

**Comment by Mehul-Kumar-27** [comment]
ok , I'll do this

**Comment by ashishmohapatra240** [comment]
Hey, I would like to work on this issue.

**Comment by nitin-787** [comment]
> Hey, I would like to work on this issue.

Sorry it got fixed check other issues
