### ISSUE TITLE
Bug: stuck at black screen on fresh app launch

### ISSUE THREAD

**Issue by SP-XD** [nitin-787/mynotes#75]
### Description

As soon as I open the app, the screen goes black and it goes to lock screen again and again. After multiple tries unlocking the screen. It finally shows the app screen content. In the debug log I might have found some leads. I am attaching them below.

### Screenshots

![Debug log](https://user-images.githubusercontent.com/69642436/193458366-84b28974-ad3a-4c18-bc8b-b393e6b6681c.png)

**Comment by SP-XD** [comment]
I got a solution I have to test, I have to update the splash screen to fit the size of the display as mentioned [here](https://github.com/flutter/flutter/issues/55691#issuecomment-620467316)

**Comment by SP-XD** [comment]
@nitin-787 I have converted every png to 9 patched png, its working but the splashscreen is getting distorted

https://user-images.githubusercontent.com/69642436/193467485-cdf8a6d0-5b29-43b6-801c-2dd3b8d74c48.mp4

Do you want to keep it like this, or let me try to create an animated splash screen with logo in the middle?

**Comment by SP-XD** [comment]
#78 for the time being I have pushed this fix. There are more important things to work like the note view, So Later We will rediscuss the splash screen again.  what are your thoughts?

**Comment by nitin-787** [comment]
> @nitin-787 I have converted every png to 9 patched png, its working but the splashscreen is getting distorted
> 
> https://user-images.githubusercontent.com/69642436/193467485-cdf8a6d0-5b29-43b6-801c-2dd3b8d74c48.mp4
> 
> Do you want to keep it like this, or let me try to create an animated splash screen with logo in the middle? 
> 

Hey this is because I made the splash scree according to my device when I just started flutter and after I forgot to change afterwards, you can raise an issue and fix it.

**Comment by nitin-787** [comment]
> #78 for the time being I have pushed this fix. There are more important things to work like the note view, So Later We will rediscuss the splash screen again.  what are your thoughts?

Yes there is a lot of work that need to done in the app.

**Comment by SP-XD** [comment]
> > @nitin-787 I have converted every png to 9 patched png, its working but the splashscreen is getting distorted
> > 
> >   
> >     
> >     
> > 
> >     Screenrecorder-2022-10-02-22-53-06-839.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > Do you want to keep it like this, or let me try to create an animated splash screen with logo in the middle?
> 
> Hey this is because I made the splash scree according to my device when I just started flutter and after I forgot to change afterwards, you can raise an issue and fix it.

Okay I will work on a fix
