### ISSUE TITLE
feat: new Splash screen implementation  

### ISSUE THREAD

**Issue by SP-XD** [nitin-787/mynotes#79]
### Description

The current splash screen was causing issues #75 . After working on the fix, the splash screen appears to be distorted as its not adaptive. So this issue is about discussing and improving and implementing an new splash screen

**Comment by SP-XD** [comment]
https://user-images.githubusercontent.com/69642436/193946211-8490dcca-c382-4802-afb8-2b948a12af7e.mp4

Added the news splash screen and Adapted the launcher icon to the theme color.
@nitin-787 feedback?

**Comment by nitin-787** [comment]
> https://user-images.githubusercontent.com/69642436/193946211-8490dcca-c382-4802-afb8-2b948a12af7e.mp4
> 
> Added the new splash screen and Adapted the launcher icon to the theme color.
> @nitin-787 feedback? 

Amazing

**Comment by nitin-787** [comment]
@SP-XD open the pull request asap!!

**Comment by SP-XD** [comment]
> @SP-XD open the pull request asap!!

done

**Comment by nitin-787** [comment]
### Fix #94
