### ISSUE TITLE
Adding Side nav-bar

### ISSUE THREAD

**Issue by piyushkumar12111111** [nitin-787/mynotes#87]
### Description

Adding side nav bar will make user experience more better ,

**Comment by piyushkumar12111111** [comment]
If accepted Assign this to me

**Comment by nitin-787** [comment]
### Hey Please provide the proper explanation like why do we need this, what kind of feature does it going contain it better if you can add ui designs as well

**Comment by piyushkumar12111111** [comment]
Sir Can i Talk to you in discord

**Comment by piyushkumar12111111** [comment]
It will have many good features

**Comment by nitin-787** [comment]
> Sir Can i Talk to you in discord

Sure
