### ISSUE TITLE
List View

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#90]
### Screenshots

https://user-images.githubusercontent.com/76255199/193972771-b6dbb3ae-3690-4019-9fbd-9c5aa9bb54e9.mp4

**Comment by ashishmohapatra240** [comment]
Hey, I would like to work on this!

**Comment by nitin-787** [comment]
> Hey, I would like to work on this!

go ahead

**Comment by nitin-787** [comment]
### Fix: #93
