### ISSUE TITLE
Improvement Internet snack_bar

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#92]
### Screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/76255199/194017251-a57e77e7-b4ba-445d-9bf0-bd814615afbc.png)

**Comment by himanshu-kashyap-au28** [comment]
it looks great too but we can go for improvement too

**Comment by ashishmohapatra240** [comment]
I can work on this!

**Comment by nitin-787** [comment]
> I can work on this!

you are already working on list view bug aren't you?

**Comment by himanshu-kashyap-au28** [comment]
> I can work on this!

great, we will be waiting

**Comment by ashishmohapatra240** [comment]
Looks good?

![image](https://user-images.githubusercontent.com/78657461/194046377-13b55d4c-cffc-4062-925a-32a9acb13663.png)

**Comment by nitin-787** [comment]
show me the implementation

**Comment by ashishmohapatra240** [comment]
The previous design looks good to me!
If you add Oops! No Internet Connection that would be better

**Comment by davidaodejobi** [comment]
Can you assign this to me, I've been looking for project all day long.

**Comment by davidaodejobi** [comment]
@nitin-787 please can I get more clarification on this task? I'm I to come up with a new design for that part of the screen, code it out, and send a PR when done?

**Comment by nitin-787** [comment]
> @nitin-787 please can I get more clarification on this task? I'm I to come up with a new design for that part of the screen, code it out, and send a PR when done?

yeah send the pr when you done.

**Comment by nitin-787** [comment]
> @nitin-787 why I'm I getting a note by default after creating a new account? Also, when the shimmer loading was on, there was an overflow error. Can I add that as an issue?

Hey you don't know about the app and started working well you can read about the app below and about the shimmer loading issue ping me discord the like is in my profile 

About App
It not an another notes sharing app instead it have some powerfull feature which make the app stand out. MyNotes is a media sharing app for student where student can share assignment, notes, tutorial, notice, etc. in any format with fellow students publically specific to their institute or in a private chat.
If any students uploads a media content then all the students in a institute will get notified this we have done using firebase cloud messaging service.
Students can chat or share any other media in private chat room, and they will get realtime send, read, delivered receipt.
Participating the Hacktoberfest?

**Comment by davidaodejobi** [comment]
![mnb](https://user-images.githubusercontent.com/63846399/194384981-b8a90acf-9916-4bd0-a087-9f31971518a5.gif)
Okay, check this out @nitin-787 , is this better?

**Comment by nitin-787** [comment]
@davidaodejobi you changed the lottie file

**Comment by davidaodejobi** [comment]
Going through the comments here, I thought that was necessary... So I changed that and added a text below.
