### ISSUE TITLE
Chat main page responsiveness

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#96]
### Screenshots

![Screenshot 2022-10-07 201840](https://user-images.githubusercontent.com/76255199/194585472-9eb54f72-12b7-4eb9-ae5c-0686fdd85b09.png)

## Figma design : https://www.figma.com/file/gfaxLApOmJRt8lFrIRrWku/UNI-Share?node-id=0%3A1
<img src="https://user-images.githubusercontent.com/76255199/194586558-33c1fc5a-1159-4960-8c68-92fd8f490586.png" height=550>

**Comment by AlsoShantanuBorkar** [comment]
Is this issue still open ? I would like to work on it.
Can you assign this to me.

**Comment by nitin-787** [comment]
@AlsoShantanuBorkar any progress?
