### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by nitin-787** [nitin-787/mynotes#98]
### Add search feature in the app for searching notes, I am 
expecting the ui may look like this but you can also your own ideas how the search feature will work 

### here is the ui part of the search!!! 👇👇

<img src="https://user-images.githubusercontent.com/76255199/193041964-4d9b17b7-6f1d-4e5b-a2b4-1c1698ed3d2e.png" height=550>

**Comment by chinmaym07** [comment]
Hey @nitin-787 , can I work on this ?

**Comment by nitin-787** [comment]
hey @chinmaym07 I already started working on this but there is a lot of things that need to done, I am creating a separate branch for and creating draft you wanna working on it ping me I'll assign it to you 

Branch link : https://github.com/nitin-787/mynotes/tree/98-search-feature

**Comment by abhishek-900** [comment]
hi can you assign me this issue ?

**Comment by nitin-787** [comment]
yeah half work is done but it not working like I want to be, I also I came up with an approach but it is not working for check the code if you can help me
